//auth
export const RECEIVE_ACCESS_TOKEN = 'RECEIVE_ACCESS_TOKEN';

//search
export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';

//tracks
export const RECEIVE_NEW_RELEASES_REQUEST = 'RECEIVE_NEW_RELEASES_REQUEST';
export const RECEIVE_NEW_RELEASES_SUCCESS = 'RECEIVE_NEW_RELEASES_SUCCESS';
export const RECEIVE_NEW_RELEASES_FAILURE = 'RECEIVE_NEW_RELEASES_FAILURE';
export const TIP_TRACK = 'TIP_TRACK';

// alerts
export const ADD_ALERT = 'ADD_ALERT';
export const DELETE_ALERT = 'DELETE_ALERT';

// player actions
export const PLAY_TRACK = 'PLAY_TRACK';