//auth
export const RECEIVE_ACCESS_TOKEN = 'RECEIVE_ACCESS_TOKEN';
export const RECEIVE_ANONYMOUS_LOGIN_INFO = 'RECEIVE_ANONYMOUS_LOGIN_INFO';
export const LOG_OUT = 'LOG_OUT';

//search
export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';

//profile
export const PROFILE_REQUEST = 'PROFILE_REQUEST';
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
export const PROFILE_FAILURE = 'PROFILE_FAILURE';

//tracks
export const RECEIVE_NEW_RELEASES_REQUEST = 'RECEIVE_NEW_RELEASES_REQUEST';
export const RECEIVE_NEW_RELEASES_SUCCESS = 'RECEIVE_NEW_RELEASES_SUCCESS';
export const RECEIVE_NEW_RELEASES_FAILURE = 'RECEIVE_NEW_RELEASES_FAILURE';

export const SEARCH_BY_GENRE_REQUEST = 'SEARCH_BY_GENRE_REQUEST';
export const SEARCH_BY_GENRE_SUCCESS = 'SEARCH_BY_GENRE_SUCCESS';
export const SEARCH_BY_GENRE_FAILURE = 'SEARCH_BY_GENRE_FAILURE';

export const SEARCH_BY_ARTIST_REQUEST = 'SEARCH_BY_ARTIST_REQUEST';
export const SEARCH_BY_ARTIST_SUCCESS = 'SEARCH_BY_ARTIST_SUCCESS';
export const SEARCH_BY_ARTIST_FAILURE = 'SEARCH_BY_ARTIST_FAILURE';

export const ADD_TO_QUEUE = 'ADD_TO_QUEUE';
export const REMOVE_FROM_QUEUE = 'REMOVE_FROM_QUEUE';

export const TIP_TRACK = 'TIP_TRACK';
export const ALLOW_NEXT_TIP = 'ALLOW_NEXT_TIP';

export const ARTIST_OF_THE_WEEK_REQUEST = 'ARTIST_OF_THE_WEEK_REQUEST';
export const ARTIST_OF_THE_WEEK_SUCCESS = 'ARTIST_OF_THE_WEEK_SUCCESS';
export const ARTIST_OF_THE_WEEK_FAILURE = 'ARTIST_OF_THE_WEEK_FAILURE';

// alerts
export const ADD_ALERT = 'ADD_ALERT';
export const DELETE_ALERT = 'DELETE_ALERT';

// player actions
export const PLAY_TRACK = 'PLAY_TRACK';
export const TOGGLE_REPEAT = 'TOGGLE_REPEAT';
export const TOGGLE_SHUFFLE = 'TOGGLE_SHUFFLE';
export const TOGGLE_PLAYER_MODE = 'TOGGLE_PLAYER_MODE';